[package]
name = "rfs-pool"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
once_cell = "1.21.3"
thiserror = "2.0.12"
toml = "0.9.5"
serde = { version = "1", features = ["derive"] }
rfs-utils = { path = "../utils" }
tokio = { version = "1", features = ["fs"] }